version: "3.5"

services:
  JoinlyTaskManagerAPI:
    image: 'node:12.18.2-alpine'
    container_name: JoinlyTaskManagerAPI
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - './api/:/home/node/app'
    working_dir: /home/node/app
    command: ["sh", "-c", "npm install && npm run dev"]
    restart: always

  JoinlyTaskManagerCLIENT:
    image: "node:12.18.2-alpine"
    container_name: JoinlyTaskManagerCLIENT
    ports:
      - '127.0.0.1:4200:4200'
    volumes:
      - "./client/:/home/node/app"
    working_dir: /home/node/app
    command: ["sh", "-c", "npm install && npm run start"]
    restart: always
